// AUTO-GENERATED by editor.html — do not edit by hand.
// Edit maze.yaml instead, then re-export.

const tree = {
  text: "Welcome to Ethos Studio. The lobby stretches out in front of you.",
  img: "media/entry.jpg",
  hotspots: [
    {
      label: "Sit on the couch",
      region: [0, 35, 9, 63],
      next: {
        text: "It's way too comfortable. You lose track of time entirely. You miss your session.",
        img: "media/couch.jpg",
        dead: true, deathText: "It's way too comfortable. You lose track of time entirely. You miss your session.",
      },
    },
    {
      label: "Sign in at the desk",
      region: [35, 38, 29, 42],
      next: {
        text: "You sign in with Bones and order a coffee. KB is ready — which way?",
        img: "media/desk.jpg",
        hotspots: [
          {
            label: "Take the left hallway",
            region: [2, 20, 22, 70],
            next: {
              text: "You step into the bathroom. Quiet in here.",
              img: "media/bathroom.jpg",
              hotspots: [
                {
                  label: "Linger a while",
                  region: [10, 30, 35, 50],
                  next: {
                    text: "Someone cranks the Sonos full volume. Vibrations knock you out. You miss everything.",
                    dead: true, deathText: "Someone cranks the Sonos full volume. Vibrations knock you out. You miss everything.",
                  },
                },
                {
                  label: "Head back to the hallway",
                  region: [55, 35, 35, 50],
                  next: {
                    text: "Back in the hallway. Three doors ahead.",
                    img: "media/hallway.jpg",
                    hotspots: [
                      {
                        label: "KB's suite",
                        region: [38, 20, 28, 60],
                        next: {
                          text: "You made it to KB's suite! Time to color.",
                          img: "media/kb.jpg",
                          win: true, winText: "You made it to KB's suite! Time to color.",
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
          {
            label: "Dante's suite",
            region: [74, 28, 22, 50],
            next: {
              text: "You're in Dante's suite. Lucy ignores you.",
              img: "media/dante.jpg",
              hotspots: [
                {
                  label: "Try to get Lucy's attention",
                  region: [30, 55, 40, 35],
                  next: {
                    text: "She never acknowledges you. You never leave.",
                    dead: true, deathText: "She never acknowledges you. You never leave.",
                  },
                },
                {
                  label: "Head back out",
                  region: [5, 30, 18, 50],
                  next: {
                    text: "Back in the hallway. KB's suite is just ahead.",
                    img: "media/hallway.jpg",
                    hotspots: [
                      {
                        label: "KB's suite",
                        region: [38, 20, 28, 60],
                        next: {
                          text: "You made it to KB's suite! Time to color.",
                          win: true, winText: "You made it to KB's suite! Time to color.",
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
};