// AUTO-GENERATED by editor.html — do not edit by hand.
// Adapted from cupcake.pdf

const tree = {
  text: 'What a delicious looking cupcake. I wonder if the gender of your baby is inside?',
  img: 'media/cupcake.jpg',

  hotspots: [
    {
      label: 'Inspect the cupcake',
      region: [28, 28, 44, 44],

      next: {
        text: 'Oh shit. There’s a sneaky little goblin up in here!',
        img: 'media/goblin.jpg',

        hotspots: [
          {
            label: 'Chase the goblin',
            region: [8, 30, 36, 40],

            next: {
              text: 'Dang that goblin just stole your baby’s gender. Are you gonna let him get away with that?',
              img: 'media/dark_hall.jpg',

              hotspots: [
                {
                  label: 'Grab a torch',
                  region: [10, 20, 28, 60],

                  next: {
                    text: 'Whoa this hallway is pretty dark and creepy.',
                    img: 'media/torch.jpg',

                    hotspots: [
                      {
                        label: 'Enter the mouse party room',
                        region: [5, 20, 28, 60],

                        next: {
                          text: 'Oops looks like there’s a mouse party in here. Better head back.',
                          img: 'media/mouse_party.jpg',

                          dead: true,
                          deathText:
                            'The mouse party completely ignores your goblin emergency. You retreat in shame.',
                        },
                      },

                      {
                        label: 'Enter the wizard room',
                        region: [60, 18, 30, 64],

                        next: {
                          text: 'Whoa this room is kinda cool. No goblins in here.',
                          img: 'media/wizard_room.jpg',

                          hotspots: [
                            {
                              label: 'Read the spell book',
                              region: [8, 22, 34, 54],

                              next: {
                                text:
                                  'A wizard spell book? Maybe there’s a spell in here for catching goblins.',
                                img: 'media/spell_book.jpg',

                                hotspots: [
                                  {
                                    label: 'Keep reading',
                                    region: [35, 30, 34, 40],

                                    next: {
                                      text:
                                        '"Hey! Don’t touch my stuff!" Oh wow — it’s the two headed nonbinary wizard.',
                                      img: 'media/wizard.jpg',

                                      hotspots: [
                                        {
                                          label: 'Ask the wizard for help',
                                          region: [28, 28, 44, 46],

                                          next: {
                                            text:
                                              'The wizard agrees to help you find your baby’s stolen gender.',
                                            img: 'media/wizard.jpg',

                                            hotspots: [
                                              {
                                                label: 'Follow the wizard',
                                                region: [40, 20, 32, 60],

                                                next: {
                                                  text:
                                                    'You follow the wizard through a trap door into a strange kitchen.',
                                                  img: 'media/kitchen.jpg',

                                                  hotspots: [
                                                    {
                                                      label: 'Look in the fridge',
                                                      region: [6, 20, 28, 60],

                                                      next: {
                                                        text:
                                                          'There are cats eating a huge fish in the fridge.',
                                                        img: 'media/fridge.jpg',

                                                        dead: true,
                                                        deathText:
                                                          'You spend too long watching the cats eat fish and the goblin escapes forever.',
                                                      },
                                                    },

                                                    {
                                                      label: 'Open the cabinet',
                                                      region: [62, 18, 28, 64],

                                                      next: {
                                                        text:
                                                          'There’s some rustling coming from this cabinet.',
                                                        img: 'media/cabinet.jpg',

                                                        hotspots: [
                                                          {
                                                            label: 'Confront the goblin',
                                                            region: [22, 24, 52, 52],

                                                            next: {
                                                              text:
                                                                'Hey! There he is! "Hand over the gender, sneak!"',
                                                              img: 'media/goblin_inside_cabinet.jpg',

                                                              hotspots: [
                                                                {
                                                                  label: 'Offer goblin snack',
                                                                  region: [30, 58, 42, 24],

                                                                  next: {
                                                                    text:
                                                                      'The goblin refuses to hand over the gender unless you have a goblin snack.',
                                                                    img: 'media/goblin_snack.jpg',

                                                                    hotspots: [
                                                                      {
                                                                        label: 'Inspect the snack',
                                                                        region: [20, 22, 56, 50],

                                                                        next: {
                                                                          text:
                                                                            'The wizard notices dust on the goblin snack bag. You blow it away and reveal it is actually POISON goblin snack.',
                                                                          img: 'media/poison_goblin_snack.jpg',

                                                                          hotspots: [
                                                                            {
                                                                              label: 'Let the wizard handle it',
                                                                              region: [26, 26, 46, 44],

                                                                              next: {
                                                                                text:
                                                                                  'The wizard strangles the goblin Bart style. "Hand over the baby gender, cretin."',
                                                                                img: 'media/bart_style.jpg',

                                                                                hotspots: [
                                                                                  {
                                                                                    label: 'Take back the baby gender',
                                                                                    region: [34, 30, 32, 42],

                                                                                    next: {
                                                                                      text:
                                                                                        'The baby gender pops out of the goblin’s back pocket.',
                                                                                      img: 'media/gender_reveal.jpg',

                                                                                      win: true,
                                                                                      winText:
                                                                                        'Congrats, your baby is awesome. All the creatures hang out together happily. THE END.',
                                                                                    },
                                                                                  },
                                                                                ],
                                                                              },
                                                                            },
                                                                          ],
                                                                        },
                                                                      },
                                                                    ],
                                                                  },
                                                                },
                                                              ],
                                                            },
                                                          },
                                                        ],
                                                      },
                                                    },
                                                  ],
                                                },
                                              },
                                            ],
                                          },
                                        },
                                      ],
                                    },
                                  },
                                ],
                              },
                            },
                          ],
                        },
                      },
                    ],
                  },
                },

                {
                  label: 'Let the goblin escape',
                  region: [58, 28, 34, 44],

                  next: {
                    text: 'You decide not to chase the goblin.',
                    img: 'media/dark_hall.jpg',

                    dead: true,
                    deathText:
                      'The goblin disappears into the darkness with your baby’s gender.',
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
};
