// AUTO-GENERATED by editor.html — do not edit by hand.
// Edit maze.yaml instead, then re-export.

const tree = {
  text: "what a delicious looking cupcake. I wonder if the gender of your baby is inside?",
  img: "media/IMG_0813.PNG",
  hotspots: [
    {
      label: "Investigate",
      region: [23, 8, 50, 82],
      next: {
        text: "oh shit. there is a sneaky little goblin up in here!",
        img: "media/IMG_0814.PNG",
        hotspots: [
          {
            label: "continue",
            region: [23, 8, 50, 82],
            next: {
              text: "what are they doing",
              img: "media/IMG_0185.PNG",
              hotspots: [
                {
                  label: "continue",
                  region: [23, 8, 50, 82],
                  next: {
                    text: "is that...?",
                    img: "media/IMG_0186.PNG",
                    hotspots: [
                      {
                        label: "continue",
                        region: [23, 8, 50, 82],
                        next: {
                          text: "dang that goblin just stole your babys gender are you gonna let them get away with that?",
                          img: "media/IMG_0187.PNG",
                        },
                      },
                    ],
                  },
                },
              ],
            },
          },
        ],
      },
    },
  ],
};
